---
- name: Installation Docker sur EC2
  hosts: all
  become: true

  tasks:
    - name: Attente connexion SSH disponible
      wait_for_connection:
        delay: 5
        timeout: 60

    - name: Installation Docker et docker-compose
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Ajout user au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Configuration registre Docker insecure
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {"insecure-registries": ["{{ registry_ip }}:443"]}
      notify: Restart Docker

    - name: Demarrage Docker
      systemd:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
